### ISSUE TITLE
Config structure

### ISSUE THREAD

**Issue by ozgio** [gamegos/freshdesk-stats#4]
- In config.js only base freshdesk url should be enough, no need for different urls for open, hold, vs
- Cases of parameter name should be in one style. lowercase or UPPERCASE, snake_case or camelCase. Usually camelCase is used in this app's config and also generally in javascript so it should be the style of the config.

**Comment by sonmezonur** [comment]
As you refer, app config files support camelcase.  Also user will be able to send request to freshdesk api by just defining domain, api key and time interval. No need to include whole url since most of it is constant.  
30ef91c9fedaa358c30fa4a6ea087f848de048eb

**Comment by ozgio** [comment]
Config parameters starts with capital letter (some calls it PascalCase). Starting letter should be lower case :)

**Comment by sonmezonur** [comment]
Got it ! :) Now config files are structured like you suggested
