### ISSUE TITLE
Support more databases

### ISSUE THREAD

**Issue by ozgio** [gamegos/freshdesk-stats#5]
Freshdesk-stats uses Sequelize under the hood. Sequelize supports PostgreSQL, MySQL, SQLite and MSSQL. This gives us opportunity to support more databases.

Not that i try but maybe removing json type in database structure make this app support all these databases.

**Comment by sonmezonur** [comment]
Since JSON extension is only enabled on Postgres, other dialects were not supported on previous model. Now this issue fixed
SHA: aad56fbbf37245e720e668d7c8dfbd1bdb64978a
