### ISSUE TITLE
Send an email if the count of the tickets increased unexpectedly

### ISSUE THREAD

**Issue by ozgio** [gamegos/freshdesk-stats#7]
If created ticket count is increased unexpectedly based on the past time ticket creations trends application should send emails. Some filters may be used for counting tickets as used in stats api. 

In the future more alert options (like sending sms, using 3rd party alert service, etc) would be added so alert structure should be more generic.

**Comment by sonmezonur** [comment]
Since we are looking for sudden peaks on dataset, nice to have some algorithm for detecting time-based thresholds.  I found similar approach on this [post](https://stackoverflow.com/a/22640362). Also it includes some quick demonstration.

**Comment by sonmezonur** [comment]
Now api supports email-based alarm system and configuration files updated. 

329e59a3d3bdcf32e03821451138185df0e23322
a672032990c487c3dd252063e8744f7bffa51dda
